bismillah 3

diff --git a/.github/workflows/tes.yml b/.github/workflows/tes.yml
--- a/.github/workflows/tes.yml
+++ b/.github/workflows/tes.yml
@@ -20,17 +20,31 @@ jobs:
         run: docker-compose up -d
 
       - name: Wait for Elgg to start
-        run: sleep 30
-
-      - name: Check Elgg availability
         run: |
-          status_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost)
-          if [ $status_code -eq 200 ]; then
-            echo "Elgg is running successfully."
-          else
-            echo "Failed to access Elgg. Status code: $status_code"
-            exit 1
-          fi
+          n=0
+          until [ $n -ge 5 ]
+          do
+            status_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost)
+            if [ $status_code -eq 200 ]; then
+              echo "Elgg is running successfully."
+              exit 0
+            else
+              echo "Failed to access Elgg. Status code: $status_code. Retrying in 10 seconds..."
+              n=$((n+1))
+              sleep 10
+            fi
+          done
+          exit 1
+
+    #   - name: Check Elgg availability
+    #     run: |
+    #       status_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost)
+    #       if [ $status_code -eq 200 ]; then
+    #         echo "Elgg is running successfully."
+    #       else
+    #         echo "Failed to access Elgg. Status code: $status_code"
+    #         exit 1
+    #       fi
 
       # Add additional steps for functional testing if needed
       # - name: Run Elgg functional tests
